const API_BASE = 'http://localhost:5000/api';

async function testGeminiIntegration() {
  console.log('======================================================================');
  console.log('🤖 TESTING GEMINI AI INTEGRATION ACROSS ENTIRE PROJECT');
  console.log('======================================================================\n');

  // Test 1: Trip Planner with Gemini AI
  console.log('1. Testing Gemini AI Trip Planner (/api/trips/generate-ai-itinerary)...');
  try {
    const res1 = await fetch(`${API_BASE}/trips/generate-ai-itinerary`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        destination: 'Ooty',
        destinationName: 'Ooty',
        numberOfDays: 3,
        travelers: 2,
        budget: 15000,
        currency: 'INR',
        travelPreference: 'nature',
      }),
    });
    const data1 = await res1.json();
    console.log('Status:', res1.status);
    console.log('Generated By:', data1.data?.executedBy || data1.data?.generatedBy);
    console.log('Destination:', data1.data?.destination);
    console.log('Days Count:', data1.data?.days?.length);
    console.log('Day 1 Title:', data1.data?.days?.[0]?.title);
    console.log('Day 1 Morning Activity:', data1.data?.days?.[0]?.morning?.spot);

    if (res1.status === 200 && data1.data?.days?.length === 3 && data1.data?.days?.[0]?.morning?.spot) {
      console.log('✅ TEST 1 PASSED: Gemini Trip Planner executed successfully!\n');
    } else {
      console.error('❌ TEST 1 FAILED:', data1);
    }
  } catch (err1) {
    console.error('❌ TEST 1 ERROR:', err1.message);
  }

  // Test 2: Chatbot with Gemini AI
  console.log('2. Testing Gemini AI Chatbot (/api/chatbot/query)...');
  try {
    const res2 = await fetch(`${API_BASE}/chatbot/query`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionId: 'test_session_' + Date.now(),
        query: 'What are the top things to do in Goa for a 4 day trip?',
        context: { language: 'en' },
      }),
    });
    const data2 = await res2.json();
    console.log('Status:', res2.status);
    console.log('Chatbot Reply Preview:\n', data2.data?.reply ? data2.data.reply.slice(0, 200) + '...' : data2.data);
    console.log('Suggestions:', data2.data?.suggestions);

    if (res2.status === 200 && data2.data?.reply) {
      console.log('✅ TEST 2 PASSED: Gemini Chatbot executed successfully!\n');
    } else {
      console.error('❌ TEST 2 FAILED:', data2);
    }
  } catch (err2) {
    console.error('❌ TEST 2 ERROR:', err2.message);
  }

  // Test 3: AI Travel Agent with Gemini AI
  console.log('3. Testing Gemini AI Travel Agent (/api/ai-agent)...');
  try {
    const res3 = await fetch(`${API_BASE}/ai-agent`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionId: 'test_agent_' + Date.now(),
        message: 'Plan a 3-day trip to Munnar Kerala for 2 people with 18000 INR budget',
      }),
    });
    const data3 = await res3.json();
    console.log('Status:', res3.status);
    console.log('Is Plan Ready:', data3.data?.isPlanReady);
    console.log('Overview:', data3.data?.tripOverview?.destination);
    console.log('Itinerary Days:', data3.data?.itinerary?.length);

    if (res3.status === 200 && data3.data?.isPlanReady && data3.data?.itinerary?.length > 0) {
      console.log('✅ TEST 3 PASSED: Gemini AI Travel Agent executed successfully!\n');
    } else {
      console.error('❌ TEST 3 FAILED:', data3);
    }
  } catch (err3) {
    console.error('❌ TEST 3 ERROR:', err3.message);
  }

  console.log('🎉 ALL GEMINI AI INTEGRATION TESTS COMPLETED SUCCESSFULLY!');
}

testGeminiIntegration().catch(console.error);
